name: "Smart Composer"
description: "Automatically classify and copy changed Markdown files using AI."
author: "FacerAin"

runs:
  using: "composite"
  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Get changed .md files
      id: changed-files
      uses: tj-actions/changed-files@v34
      with:
        files: ${{ inputs.uploads_pattern }}
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install openai
      shell: bash

    - name: Classify & copy via Python
      shell: bash
      run: |
        echo "Changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
        python $GITHUB_ACTION_PATH/main.py \
          --changed-files "${{ steps.changed-files.outputs.all_changed_files }}" \
          --categories "${{ inputs.categories }}" \
          --docs-dir "${{ inputs.docs_dir }}"
      env:
        OPENAI_API_KEY: ${{ inputs.openai_api_key }}

inputs:
  openai_api_key:
    description: "OpenAI API Key"
    required: true

  categories:
    description: "Comma-separated list of categories"
    required: false
    default: "Python,JavaScript,DevOps,Database,Etc"

  uploads_pattern:
    description: "Glob pattern for uploaded MD files (e.g. 'uploads/*.md')"
    required: false
    default: "uploads/*.md"

  docs_dir:
    description: "Destination folder for categorized files"
    required: false
    default: "docs"
